### ISSUE TITLE
Is llvm-assignment using llvm/clang version 4.0.0?

### ISSUE THREAD

**Issue by ellisy0** [lijiansong/clang-llvm-tutorial#2]
Hi, I'm trying to do something with `function-pointer-analysis` but couldn't compile `LLVMAssignment.cpp` using clang/llvm 4.0.0:
```
Compiling LLVMAssignment.cpp
/home/yves/Workspace/c-function-pointer/clang-llvm-tutorial/function-pointer-analysis/LLVMAssignment.cpp:15:10: fatal error: 'llvm/Bitcode/ReaderWriter.h' file not found
#include <llvm/Bitcode/ReaderWriter.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
Turns out version 4.0.0 already [separated this header into different files](https://reviews.llvm.org/D26502). I've also tried 3.9.0 which is before this commit, or just copying the 3.9.0 headers to compile and use later versions of clang/g++ to link, but these didn't work either; there was a lot of API changes.

**Comment by lijiansong** [comment]
@yvesyy Thanks for your report.
This project is based on clang/llvm 4.0.0.
I have already fixed this header including error.
As mentioned in this commit history: <https://reviews.llvm.org/D26502>,
Just comment out the old header file and replace them with the two separate header:

```
//#include <llvm/Bitcode/ReaderWriter.h>
#include <llvm/Bitcode/BitcodeReader.h>
#include <llvm/Bitcode/BitcodeWriter.h>
```
